spring:
  datasource:

    hikari:
      jdbc-url: jdbc:mariadb://localhost:13306/chatting_db
      username: root
      password: root_password
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: ConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql

logging:
  level:
    root: info
    com.example.chatting: debug
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

